name: Publish to Winget

on:
  release:
    types: [published]

env:
  REGEX: 'wsl\.([\d.]+)\.x64\.msi$'

jobs:
  publish:
    runs-on: windows-latest # Action can only run on Windows
    steps:
      - name: Publish WSL
        run: |
          $assets = '${{ toJSON(github.event.release.assets) }}' | ConvertFrom-Json
          $wingetRelevantAsset = $assets | Where-Object { $_.name -like '*.msi' } | Select-Object -First 1
          $regex = [Regex]::New($env:REGEX)
          $version = $regex.Match($wingetRelevantAsset.name).Groups[1].Value

          Write-Output "Asset info: $assets"
          Write-Output "Relevant asset: $wingetRelevantAsset"

          $wingetPackage = "Microsoft.WSL"

          & curl.exe -JLO https://aka.ms/wingetcreate/latest
          & .\wingetcreate.exe update $wingetPackage -s -v $version -u $wingetRelevantAsset.browser_download_url -t "${{ secrets.WINGET_TOKEN }}"